name: Deploy React site to Pages

on:
    push:
        branches: 
            - gh-pages
    pull_request: 
        branches: 
            - gh-pages
    workflow_dispatch: 

permissions: 
    contents: read
    pages: write
    id-token: write

concurrency: 
    cancel-in-progress: false
    group: "pages"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 2

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                cache: pnpm
                cache-dependency-path: pnpm-lock.yaml
                node-version-file: .tool-versions
            
            - name: Install dependencies
              uses: pnpm install --frozen-lockfile

            - name: Build with React.js
              uses: pnpm run build

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: dist
    deploy:
        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
